brand_name:
  default: "Khulnasoft"
website_url:
  default: "https://khulnasoft.com"
logo_url:
  default: "https://github.com/khulnasoft/developer-relations/blob/main/community/Assets/logo_for_brand_header.png?raw=true"
mobile_logo_url:
  default: "https://github.com/khulnasoft/developer-relations/blob/main/community/Assets/logo_for_brand_header.png?raw=true"
links:
  type: list
  list_type: simple
  default: >-
    Get the Agent, https://learn.khulnasoft.com/docs/get, _blank|
    Sign into Cloud, https://app.khulnasoft.com, _blank|
    Khulnasoft Learn, https://learn.khulnasoft.com, _blank|
    Help, https://khulnasoft.com/community, _blank
icons:
  type: list
  list_type: simple
  default: ""
  description: "Format: icon-name,url,target (optional)"
custom_font_awesome_icons:
  type: list
  list_type: simple
  default: ""
  description: "List of FontAwesome 5 icons used in this theme component"
show_bar_on_mobile:
  type: bool
  default: false
